/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SocialLink = {
  _type: "socialLink";
  platform:
    | "facebook"
    | "instagram"
    | "linkedin"
    | "x"
    | "youtube"
    | "tiktok"
    | "whatsapp";
  url: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  socialImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  noIndex?: boolean;
};

export type ProgrammeReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "programme";
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type CampaignReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "campaign";
};

export type StoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "story";
};

export type EventReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "event";
};

export type OpportunityReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "opportunity";
};

export type Link = {
  _type: "link";
  label: string;
  linkType: "internal" | "external";
  internalLink?:
    | ProgrammeReference
    | ProjectReference
    | CampaignReference
    | StoryReference
    | EventReference
    | OpportunityReference;
  url?: string;
  openInNewTab?: boolean;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<
        | {
            href: string;
            openInNewTab?: boolean;
            _type: "externalLink";
            _key: string;
          }
        | {
            reference:
              | ProgrammeReference
              | ProjectReference
              | CampaignReference
              | StoryReference
              | EventReference
              | OpportunityReference;
            _type: "internalLink";
            _key: string;
          }
      >;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      caption?: string;
      _type: "image";
      _key: string;
    }
>;

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question: string;
  answer: string;
  category:
    | "general"
    | "programmes"
    | "contributions"
    | "opportunities"
    | "partnerships"
    | "other";
  featured?: boolean;
  order: number;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Report = {
  _id: string;
  _type: "report";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  reportType:
    | "annual"
    | "impact"
    | "financial"
    | "programme"
    | "project"
    | "research"
    | "other";
  description: string;
  publicationDate: string;
  reportingPeriod?: string;
  file: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  programme?: ProgrammeReference;
  project?: ProjectReference;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  featured?: boolean;
  order?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote: string;
  name: string;
  testimonialType:
    "participant" | "community" | "volunteer" | "partner" | "other";
  role?: string;
  organisation?: string;
  programme?: ProgrammeReference;
  project?: ProjectReference;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  featured?: boolean;
  order: number;
};

export type ImpactMetric = {
  _id: string;
  _type: "impactMetric";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  value: number;
  prefix?: string;
  suffix?: string;
  description?: string;
  asOfDate: string;
  programme?: ProgrammeReference;
  project?: ProjectReference;
  featured?: boolean;
  order: number;
};

export type Partner = {
  _id: string;
  _type: "partner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  partnerType:
    | "strategic"
    | "funding"
    | "implementation"
    | "institutional"
    | "supporting"
    | "other";
  description?: string;
  websiteUrl?: string;
  programmes?: Array<
    {
      _key: string;
    } & ProgrammeReference
  >;
  projects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  featured?: boolean;
  order: number;
};

export type TeamMember = {
  _id: string;
  _type: "teamMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  role: string;
  group: "leadership" | "board" | "team" | "advisory";
  bio?: string;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  linkedinUrl?: string;
  order: number;
};

export type Programme = {
  _id: string;
  _type: "programme";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  shortDescription: string;
  content: BlockContent;
  focusAreas?: Array<string>;
  featuredImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  featured?: boolean;
  order: number;
  seo?: Seo;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  programme: ProgrammeReference;
  shortDescription: string;
  content: BlockContent;
  status: "planned" | "active" | "onHold" | "completed" | "cancelled";
  startDate?: string;
  endDate?: string;
  location?: string;
  featuredImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  featured?: boolean;
  seo?: Seo;
};

export type Campaign = {
  _id: string;
  _type: "campaign";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  shortDescription: string;
  content: BlockContent;
  programme: ProgrammeReference;
  project?: ProjectReference;
  status: "upcoming" | "active" | "paused" | "completed" | "cancelled";
  startDate?: string;
  endDate?: string;
  goalAmount: number;
  currency: "TZS" | "USD";
  featuredImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  featured?: boolean;
  seo?: Seo;
};

export type Story = {
  _id: string;
  _type: "story";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  storyType: "impact" | "news" | "update";
  excerpt: string;
  content: BlockContent;
  publishedAt: string;
  programme?: ProgrammeReference;
  project?: ProjectReference;
  campaign?: CampaignReference;
  featuredImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  featured?: boolean;
  seo?: Seo;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  shortDescription: string;
  content: BlockContent;
  startAt: string;
  endAt?: string;
  format: "inPerson" | "online" | "hybrid";
  venue?: string;
  location?: string;
  onlineUrl?: string;
  programme?: ProgrammeReference;
  project?: ProjectReference;
  participationLink?: Link;
  featuredImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  featured?: boolean;
  seo?: Seo;
};

export type Opportunity = {
  _id: string;
  _type: "opportunity";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  opportunityType:
    | "volunteer"
    | "internship"
    | "employment"
    | "partnership"
    | "programmeApplication"
    | "other";
  shortDescription: string;
  content: BlockContent;
  mode: "onSite" | "remote" | "hybrid";
  location?: string;
  deadline?: string;
  programme?: ProgrammeReference;
  project?: ProjectReference;
  applicationLink?: Link;
  featuredImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  featured?: boolean;
  seo?: Seo;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type ContactInformation = {
  _id: string;
  _type: "contactInformation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  primaryEmail: string;
  secondaryEmail?: string;
  primaryPhone: string;
  secondaryPhone?: string;
  whatsappNumber?: string;
  addressLine?: string;
  district?: string;
  city: string;
  country: string;
  postalAddress?: string;
  mapUrl?: string;
  officeHours?: Array<{
    days: string;
    hours: string;
    _type: "officeHoursEntry";
    _key: string;
  }>;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  homePage?: {
    hero?: {
      title: string;
      description: string;
      imageAlt: string;
      image?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        _type: "image";
      };
    };
    introduction?: {
      title: string;
      description: string;
    };
    impact?: {
      title: string;
    };
    work?: {
      title: string;
      description: string;
    };
    projects?: {
      title: string;
      description: string;
    };
    involvement?: {
      title: string;
      description: string;
      volunteerDescription: string;
      partnerDescription: string;
      supportDescription: string;
    };
    contribution?: {
      title: string;
      description: string;
    };
    seo?: Seo;
  };
  aboutPage?: {
    introduction?: {
      title: string;
      summary: string;
      description: string;
      imageAlt: string;
      image?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        _type: "image";
      };
    };
    purpose?: {
      title: string;
      description: string;
      missionTitle: string;
      missionDescription: string;
      visionTitle: string;
      visionDescription: string;
    };
    story?: {
      title: string;
      description: string;
      introduction: string;
      paragraph1: string;
      paragraph2: string;
      paragraph3: string;
      closing: string;
    };
    principles?: {
      title: string;
      description: string;
      items: Array<{
        title: string;
        description: string;
        _type: "principle";
        _key: string;
      }>;
    };
    team?: {
      title: string;
      description: string;
    };
    header?: {
      title: string;
      description: string;
    };
    seo?: Seo;
  };
  ourWorkPage?: {
    header?: {
      title: string;
      description: string;
    };
    seo?: Seo;
  };
  siteTitle: string;
  tagline: string;
  siteDescription: string;
  contributionCta?: Link;
  getInvolvedCta?: Link;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  footerDescription?: string;
  copyrightText?: string;
  seo?: Seo;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SocialLink
  | SanityImageAssetReference
  | Seo
  | ProgrammeReference
  | ProjectReference
  | CampaignReference
  | StoryReference
  | EventReference
  | OpportunityReference
  | Link
  | BlockContent
  | Faq
  | SanityFileAssetReference
  | Report
  | SanityImageCrop
  | SanityImageHotspot
  | Testimonial
  | ImpactMetric
  | Partner
  | TeamMember
  | Programme
  | Project
  | Campaign
  | Story
  | Event
  | Opportunity
  | Slug
  | ContactInformation
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/queries/campaigns.ts
// Variable: CAMPAIGNS_QUERY
// Query: *[_type == "campaign"] | order(startDate desc, title asc) {    _id,    title,    "slug": slug.current,    shortDescription,    status,    startDate,    endDate,    goalAmount,    currency,    programme-> {      _id,      title,      "slug": slug.current    },    project-> {      _id,      title,      "slug": slug.current    },    featuredImage {      asset,      alt,      hotspot,      crop    },    featured  }
export type CAMPAIGNS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  shortDescription: string;
  status: "active" | "cancelled" | "completed" | "paused" | "upcoming";
  startDate: string | null;
  endDate: string | null;
  goalAmount: number;
  currency: "TZS" | "USD";
  programme: {
    _id: string;
    title: string;
    slug: string;
  };
  project: {
    _id: string;
    title: string;
    slug: string;
  } | null;
  featuredImage: {
    asset: SanityImageAssetReference | null;
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  };
  featured: boolean | null;
}>;

// Source: sanity/queries/campaigns.ts
// Variable: CAMPAIGN_BY_SLUG_QUERY
// Query: *[_type == "campaign" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    shortDescription,    content[] {      ...,      markDefs[] {        ...,        _type == "internalLink" => {          ...,          reference-> {            _type,            "slug": slug.current          }        }      },      _type == "image" => {        asset,        alt,        caption,        hotspot,        crop      }    },    status,    startDate,    endDate,    goalAmount,    currency,    programme-> {      _id,      title,      "slug": slug.current,      shortDescription    },    project-> {      _id,      title,      "slug": slug.current,      shortDescription,      status    },    featuredImage {      asset,      alt,      hotspot,      crop    },    featured,    seo {      metaTitle,      metaDescription,      socialImage {        asset,        crop,        hotspot,        alt      },      noIndex    }  }
export type CAMPAIGN_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  shortDescription: string;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<
          | {
              href: string;
              openInNewTab?: boolean;
              _type: "externalLink";
              _key: string;
            }
          | {
              reference:
                | {
                    _type: "campaign";
                    slug: string;
                  }
                | {
                    _type: "event";
                    slug: string;
                  }
                | {
                    _type: "opportunity";
                    slug: string;
                  }
                | {
                    _type: "programme";
                    slug: string;
                  }
                | {
                    _type: "project";
                    slug: string;
                  }
                | {
                    _type: "story";
                    slug: string;
                  };
              _type: "internalLink";
              _key: string;
            }
        > | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset: SanityImageAssetReference | null;
        media?: unknown;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        alt: string;
        caption: string | null;
        _type: "image";
        _key: string;
        markDefs: null;
      }
  >;
  status: "active" | "cancelled" | "completed" | "paused" | "upcoming";
  startDate: string | null;
  endDate: string | null;
  goalAmount: number;
  currency: "TZS" | "USD";
  programme: {
    _id: string;
    title: string;
    slug: string;
    shortDescription: string;
  };
  project: {
    _id: string;
    title: string;
    slug: string;
    shortDescription: string;
    status: "active" | "cancelled" | "completed" | "onHold" | "planned";
  } | null;
  featuredImage: {
    asset: SanityImageAssetReference | null;
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  };
  featured: boolean | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    socialImage: {
      asset: SanityImageAssetReference | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      alt: string;
    } | null;
    noIndex: boolean | null;
  } | null;
} | null;

// Source: sanity/queries/contact-information.ts
// Variable: CONTACT_INFORMATION_QUERY
// Query: *[_type == "contactInformation" && _id == "contactInformation"][0] {    _id,    primaryEmail,    secondaryEmail,    primaryPhone,    secondaryPhone,    whatsappNumber,    addressLine,    district,    city,    country,    postalAddress,    mapUrl,    officeHours[] {      days,      hours    }  }
export type CONTACT_INFORMATION_QUERY_RESULT = {
  _id: "contactInformation";
  primaryEmail: string;
  secondaryEmail: string | null;
  primaryPhone: string;
  secondaryPhone: string | null;
  whatsappNumber: string | null;
  addressLine: string | null;
  district: string | null;
  city: string;
  country: string;
  postalAddress: string | null;
  mapUrl: string | null;
  officeHours: Array<{
    days: string;
    hours: string;
  }> | null;
} | null;

// Source: sanity/queries/events.ts
// Variable: EVENTS_QUERY
// Query: *[_type == "event"] | order(startAt asc, title asc) {    _id,    title,    "slug": slug.current,    shortDescription,    startAt,    endAt,    format,    venue,    location,    programme-> {      _id,      title,      "slug": slug.current    },    project-> {      _id,      title,      "slug": slug.current    },    featuredImage {      asset,      alt,      hotspot,      crop    },    featured  }
export type EVENTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  shortDescription: string;
  startAt: string;
  endAt: string | null;
  format: "hybrid" | "inPerson" | "online";
  venue: string | null;
  location: string | null;
  programme: {
    _id: string;
    title: string;
    slug: string;
  } | null;
  project: {
    _id: string;
    title: string;
    slug: string;
  } | null;
  featuredImage: {
    asset: SanityImageAssetReference | null;
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  };
  featured: boolean | null;
}>;

// Source: sanity/queries/events.ts
// Variable: EVENT_BY_SLUG_QUERY
// Query: *[_type == "event" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    shortDescription,    content[] {      ...,      markDefs[] {        ...,        _type == "internalLink" => {          ...,          reference-> {            _type,            "slug": slug.current          }        }      },      _type == "image" => {        asset,        alt,        caption,        hotspot,        crop      }    },    startAt,    endAt,    format,    venue,    location,    onlineUrl,    programme-> {      _id,      title,      "slug": slug.current,      shortDescription    },    project-> {      _id,      title,      "slug": slug.current,      shortDescription,      status    },    participationLink {      label,      linkType,      internalLink-> {        _type,        "slug": slug.current      },      url,      openInNewTab    },    featuredImage {      asset,      alt,      hotspot,      crop    },    featured,    seo {      metaTitle,      metaDescription,      socialImage {        asset,        crop,        hotspot,        alt      },      noIndex    }  }
export type EVENT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  shortDescription: string;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<
          | {
              href: string;
              openInNewTab?: boolean;
              _type: "externalLink";
              _key: string;
            }
          | {
              reference:
                | {
                    _type: "campaign";
                    slug: string;
                  }
                | {
                    _type: "event";
                    slug: string;
                  }
                | {
                    _type: "opportunity";
                    slug: string;
                  }
                | {
                    _type: "programme";
                    slug: string;
                  }
                | {
                    _type: "project";
                    slug: string;
                  }
                | {
                    _type: "story";
                    slug: string;
                  };
              _type: "internalLink";
              _key: string;
            }
        > | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset: SanityImageAssetReference | null;
        media?: unknown;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        alt: string;
        caption: string | null;
        _type: "image";
        _key: string;
        markDefs: null;
      }
  >;
  startAt: string;
  endAt: string | null;
  format: "hybrid" | "inPerson" | "online";
  venue: string | null;
  location: string | null;
  onlineUrl: string | null;
  programme: {
    _id: string;
    title: string;
    slug: string;
    shortDescription: string;
  } | null;
  project: {
    _id: string;
    title: string;
    slug: string;
    shortDescription: string;
    status: "active" | "cancelled" | "completed" | "onHold" | "planned";
  } | null;
  participationLink: {
    label: string;
    linkType: "external" | "internal";
    internalLink:
      | {
          _type: "campaign";
          slug: string;
        }
      | {
          _type: "event";
          slug: string;
        }
      | {
          _type: "opportunity";
          slug: string;
        }
      | {
          _type: "programme";
          slug: string;
        }
      | {
          _type: "project";
          slug: string;
        }
      | {
          _type: "story";
          slug: string;
        }
      | null;
    url: string | null;
    openInNewTab: boolean | null;
  } | null;
  featuredImage: {
    asset: SanityImageAssetReference | null;
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  };
  featured: boolean | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    socialImage: {
      asset: SanityImageAssetReference | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      alt: string;
    } | null;
    noIndex: boolean | null;
  } | null;
} | null;

// Source: sanity/queries/faqs.ts
// Variable: FAQS_QUERY
// Query: *[_type == "faq"] | order(category asc, order asc, question asc) {    _id,    question,    answer,    category,    featured,    order  }
export type FAQS_QUERY_RESULT = Array<{
  _id: string;
  question: string;
  answer: string;
  category:
    | "contributions"
    | "general"
    | "opportunities"
    | "other"
    | "partnerships"
    | "programmes";
  featured: boolean | null;
  order: number;
}>;

// Source: sanity/queries/impact-metrics.ts
// Variable: IMPACT_METRICS_QUERY
// Query: *[_type == "impactMetric"] | order(order asc, title asc) {    _id,    title,    value,    prefix,    suffix,    description,    asOfDate,    programme-> {      _id,      title,      "slug": slug.current    },    project-> {      _id,      title,      "slug": slug.current,      status    },    featured,    order  }
export type IMPACT_METRICS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  value: number;
  prefix: string | null;
  suffix: string | null;
  description: string | null;
  asOfDate: string;
  programme: {
    _id: string;
    title: string;
    slug: string;
  } | null;
  project: {
    _id: string;
    title: string;
    slug: string;
    status: "active" | "cancelled" | "completed" | "onHold" | "planned";
  } | null;
  featured: boolean | null;
  order: number;
}>;

// Source: sanity/queries/impact-metrics.ts
// Variable: FEATURED_IMPACT_METRICS_QUERY
// Query: *[_type == "impactMetric" && featured == true && title != "" && defined(title) && defined(value)]    | order(order asc, title asc)[0...4] {      _id, title, value, prefix, suffix    }
export type FEATURED_IMPACT_METRICS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  value: number;
  prefix: string | null;
  suffix: string | null;
}>;

// Source: sanity/queries/opportunities.ts
// Variable: OPPORTUNITIES_QUERY
// Query: *[_type == "opportunity"] | order(deadline asc, title asc) {    _id,    title,    "slug": slug.current,    opportunityType,    shortDescription,    mode,    location,    deadline,    programme-> {      _id,      title,      "slug": slug.current    },    project-> {      _id,      title,      "slug": slug.current    },    featuredImage {      asset,      alt,      hotspot,      crop    },    featured  }
export type OPPORTUNITIES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  opportunityType:
    | "employment"
    | "internship"
    | "other"
    | "partnership"
    | "programmeApplication"
    | "volunteer";
  shortDescription: string;
  mode: "hybrid" | "onSite" | "remote";
  location: string | null;
  deadline: string | null;
  programme: {
    _id: string;
    title: string;
    slug: string;
  } | null;
  project: {
    _id: string;
    title: string;
    slug: string;
  } | null;
  featuredImage: {
    asset: SanityImageAssetReference | null;
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  featured: boolean | null;
}>;

// Source: sanity/queries/opportunities.ts
// Variable: OPPORTUNITY_BY_SLUG_QUERY
// Query: *[_type == "opportunity" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    opportunityType,    shortDescription,    content[] {      ...,      markDefs[] {        ...,        _type == "internalLink" => {          ...,          reference-> {            _type,            "slug": slug.current          }        }      },      _type == "image" => {        asset,        alt,        caption,        hotspot,        crop      }    },    mode,    location,    deadline,    programme-> {      _id,      title,      "slug": slug.current,      shortDescription    },    project-> {      _id,      title,      "slug": slug.current,      shortDescription,      status    },    applicationLink {      label,      linkType,      internalLink-> {        _type,        "slug": slug.current      },      url,      openInNewTab    },    featuredImage {      asset,      alt,      hotspot,      crop    },    featured,    seo {      metaTitle,      metaDescription,      socialImage {        asset,        crop,        hotspot,        alt      },      noIndex    }  }
export type OPPORTUNITY_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  opportunityType:
    | "employment"
    | "internship"
    | "other"
    | "partnership"
    | "programmeApplication"
    | "volunteer";
  shortDescription: string;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<
          | {
              href: string;
              openInNewTab?: boolean;
              _type: "externalLink";
              _key: string;
            }
          | {
              reference:
                | {
                    _type: "campaign";
                    slug: string;
                  }
                | {
                    _type: "event";
                    slug: string;
                  }
                | {
                    _type: "opportunity";
                    slug: string;
                  }
                | {
                    _type: "programme";
                    slug: string;
                  }
                | {
                    _type: "project";
                    slug: string;
                  }
                | {
                    _type: "story";
                    slug: string;
                  };
              _type: "internalLink";
              _key: string;
            }
        > | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset: SanityImageAssetReference | null;
        media?: unknown;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        alt: string;
        caption: string | null;
        _type: "image";
        _key: string;
        markDefs: null;
      }
  >;
  mode: "hybrid" | "onSite" | "remote";
  location: string | null;
  deadline: string | null;
  programme: {
    _id: string;
    title: string;
    slug: string;
    shortDescription: string;
  } | null;
  project: {
    _id: string;
    title: string;
    slug: string;
    shortDescription: string;
    status: "active" | "cancelled" | "completed" | "onHold" | "planned";
  } | null;
  applicationLink: {
    label: string;
    linkType: "external" | "internal";
    internalLink:
      | {
          _type: "campaign";
          slug: string;
        }
      | {
          _type: "event";
          slug: string;
        }
      | {
          _type: "opportunity";
          slug: string;
        }
      | {
          _type: "programme";
          slug: string;
        }
      | {
          _type: "project";
          slug: string;
        }
      | {
          _type: "story";
          slug: string;
        }
      | null;
    url: string | null;
    openInNewTab: boolean | null;
  } | null;
  featuredImage: {
    asset: SanityImageAssetReference | null;
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  featured: boolean | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    socialImage: {
      asset: SanityImageAssetReference | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      alt: string;
    } | null;
    noIndex: boolean | null;
  } | null;
} | null;

// Source: sanity/queries/page-content.ts
// Variable: HOME_CONTENT_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0].homePage {    hero { title, description, imageAlt, image { asset, alt, crop, hotspot } },    introduction { title, description },    impact { title },    work { title, description },    projects { title, description },    involvement { title, description, volunteerDescription, partnerDescription, supportDescription },    contribution { title, description },    seo { metaTitle, metaDescription, noIndex, socialImage { asset, alt, crop, hotspot } }  }
export type HOME_CONTENT_QUERY_RESULT = {
  hero: {
    title: string;
    description: string;
    imageAlt: string;
    image: {
      asset: SanityImageAssetReference | null;
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
  } | null;
  introduction: {
    title: string;
    description: string;
  } | null;
  impact: {
    title: string;
  } | null;
  work: {
    title: string;
    description: string;
  } | null;
  projects: {
    title: string;
    description: string;
  } | null;
  involvement: {
    title: string;
    description: string;
    volunteerDescription: string;
    partnerDescription: string;
    supportDescription: string;
  } | null;
  contribution: {
    title: string;
    description: string;
  } | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    noIndex: boolean | null;
    socialImage: {
      asset: SanityImageAssetReference | null;
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
  } | null;
} | null;

// Source: sanity/queries/page-content.ts
// Variable: ABOUT_CONTENT_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0].aboutPage {    introduction { title, summary, description, imageAlt, image { asset, alt, crop, hotspot } },    purpose { title, description, missionTitle, missionDescription, visionTitle, visionDescription },    story { title, description, introduction, paragraph1, paragraph2, paragraph3, closing },    principles { title, description, items[] { _key, title, description } },    team { title, description },    header { title, description },    seo { metaTitle, metaDescription, noIndex, socialImage { asset, alt, crop, hotspot } }  }
export type ABOUT_CONTENT_QUERY_RESULT = {
  introduction: {
    title: string;
    summary: string;
    description: string;
    imageAlt: string;
    image: {
      asset: SanityImageAssetReference | null;
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
  } | null;
  purpose: {
    title: string;
    description: string;
    missionTitle: string;
    missionDescription: string;
    visionTitle: string;
    visionDescription: string;
  } | null;
  story: {
    title: string;
    description: string;
    introduction: string;
    paragraph1: string;
    paragraph2: string;
    paragraph3: string;
    closing: string;
  } | null;
  principles: {
    title: string;
    description: string;
    items: Array<{
      _key: string;
      title: string;
      description: string;
    }>;
  } | null;
  team: {
    title: string;
    description: string;
  } | null;
  header: {
    title: string;
    description: string;
  } | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    noIndex: boolean | null;
    socialImage: {
      asset: SanityImageAssetReference | null;
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
  } | null;
} | null;

// Source: sanity/queries/page-content.ts
// Variable: OUR_WORK_CONTENT_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0].ourWorkPage {    header { title, description },    seo { metaTitle, metaDescription, noIndex, socialImage { asset, alt, crop, hotspot } }  }
export type OUR_WORK_CONTENT_QUERY_RESULT = {
  header: {
    title: string;
    description: string;
  } | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    noIndex: boolean | null;
    socialImage: {
      asset: SanityImageAssetReference | null;
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
  } | null;
} | null;

// Source: sanity/queries/partners.ts
// Variable: PARTNERS_QUERY
// Query: *[_type == "partner"] | order(order asc, name asc) {    _id,    name,    partnerType,    description,    websiteUrl,    programmes[]-> {      _id,      title,      "slug": slug.current    },    projects[]-> {      _id,      title,      "slug": slug.current,      status    },    logo {      asset,      alt,      hotspot,      crop    },    featured,    order  }
export type PARTNERS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  partnerType:
    | "funding"
    | "implementation"
    | "institutional"
    | "other"
    | "strategic"
    | "supporting";
  description: string | null;
  websiteUrl: string | null;
  programmes: Array<{
    _id: string;
    title: string;
    slug: string;
  }> | null;
  projects: Array<{
    _id: string;
    title: string;
    slug: string;
    status: "active" | "cancelled" | "completed" | "onHold" | "planned";
  }> | null;
  logo: {
    asset: SanityImageAssetReference | null;
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  };
  featured: boolean | null;
  order: number;
}>;

// Source: sanity/queries/programmes.ts
// Variable: PROGRAMMES_QUERY
// Query: *[_type == "programme"] | order(order asc, title asc) {    _id,    title,    "slug": slug.current,    shortDescription,    focusAreas,    featuredImage {      asset,      alt,      hotspot,      crop    },    featured,    order  }
export type PROGRAMMES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  shortDescription: string;
  focusAreas: Array<string> | null;
  featuredImage: {
    asset: SanityImageAssetReference | null;
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  };
  featured: boolean | null;
  order: number;
}>;

// Source: sanity/queries/programmes.ts
// Variable: PROGRAMME_BY_SLUG_QUERY
// Query: *[_type == "programme" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    shortDescription,    content[] {      ...,      markDefs[] {        ...,        _type == "internalLink" => {          ...,          reference-> {            _type,            "slug": slug.current          }        }      },      _type == "image" => {        asset,        alt,        caption,        hotspot,        crop      }    },    focusAreas,    featuredImage {      asset,      alt,      hotspot,      crop    },    featured,    order,    seo {      metaTitle,      metaDescription,      socialImage {        asset,        crop,        hotspot,        alt      },      noIndex    }  }
export type PROGRAMME_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  shortDescription: string;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<
          | {
              href: string;
              openInNewTab?: boolean;
              _type: "externalLink";
              _key: string;
            }
          | {
              reference:
                | {
                    _type: "campaign";
                    slug: string;
                  }
                | {
                    _type: "event";
                    slug: string;
                  }
                | {
                    _type: "opportunity";
                    slug: string;
                  }
                | {
                    _type: "programme";
                    slug: string;
                  }
                | {
                    _type: "project";
                    slug: string;
                  }
                | {
                    _type: "story";
                    slug: string;
                  };
              _type: "internalLink";
              _key: string;
            }
        > | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset: SanityImageAssetReference | null;
        media?: unknown;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        alt: string;
        caption: string | null;
        _type: "image";
        _key: string;
        markDefs: null;
      }
  >;
  focusAreas: Array<string> | null;
  featuredImage: {
    asset: SanityImageAssetReference | null;
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  };
  featured: boolean | null;
  order: number;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    socialImage: {
      asset: SanityImageAssetReference | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      alt: string;
    } | null;
    noIndex: boolean | null;
  } | null;
} | null;

// Source: sanity/queries/programmes.ts
// Variable: PROGRAMME_CARDS_QUERY
// Query: *[_type == "programme" && defined(slug.current) && slug.current != "" && defined(title) && title != ""]    | order(order asc, title asc) {      _id, title, "slug": slug.current, shortDescription    }
export type PROGRAMME_CARDS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  shortDescription: string;
}>;

// Source: sanity/queries/projects.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"] | order(startDate desc, title asc) {    _id,    title,    "slug": slug.current,    shortDescription,    status,    startDate,    endDate,    location,    programme-> {      _id,      title,      "slug": slug.current    },    featuredImage {      asset,      alt,      hotspot,      crop    },    featured  }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  shortDescription: string;
  status: "active" | "cancelled" | "completed" | "onHold" | "planned";
  startDate: string | null;
  endDate: string | null;
  location: string | null;
  programme: {
    _id: string;
    title: string;
    slug: string;
  };
  featuredImage: {
    asset: SanityImageAssetReference | null;
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  };
  featured: boolean | null;
}>;

// Source: sanity/queries/projects.ts
// Variable: PROJECT_BY_SLUG_QUERY
// Query: *[_type == "project" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    shortDescription,    content[] {      ...,      markDefs[] {        ...,        _type == "internalLink" => {          ...,          reference-> {            _type,            "slug": slug.current          }        }      },      _type == "image" => {        asset,        alt,        caption,        hotspot,        crop      }    },    status,    startDate,    endDate,    location,    programme-> {      _id,      title,      "slug": slug.current,      shortDescription    },    featuredImage {      asset,      alt,      hotspot,      crop    },    featured,    seo {      metaTitle,      metaDescription,      socialImage {        asset,        crop,        hotspot,        alt      },      noIndex    }  }
export type PROJECT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  shortDescription: string;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<
          | {
              href: string;
              openInNewTab?: boolean;
              _type: "externalLink";
              _key: string;
            }
          | {
              reference:
                | {
                    _type: "campaign";
                    slug: string;
                  }
                | {
                    _type: "event";
                    slug: string;
                  }
                | {
                    _type: "opportunity";
                    slug: string;
                  }
                | {
                    _type: "programme";
                    slug: string;
                  }
                | {
                    _type: "project";
                    slug: string;
                  }
                | {
                    _type: "story";
                    slug: string;
                  };
              _type: "internalLink";
              _key: string;
            }
        > | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset: SanityImageAssetReference | null;
        media?: unknown;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        alt: string;
        caption: string | null;
        _type: "image";
        _key: string;
        markDefs: null;
      }
  >;
  status: "active" | "cancelled" | "completed" | "onHold" | "planned";
  startDate: string | null;
  endDate: string | null;
  location: string | null;
  programme: {
    _id: string;
    title: string;
    slug: string;
    shortDescription: string;
  };
  featuredImage: {
    asset: SanityImageAssetReference | null;
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  };
  featured: boolean | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    socialImage: {
      asset: SanityImageAssetReference | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      alt: string;
    } | null;
    noIndex: boolean | null;
  } | null;
} | null;

// Source: sanity/queries/projects.ts
// Variable: FEATURED_PROJECTS_QUERY
// Query: *[_type == "project" && featured == true &&    defined(slug.current) && slug.current != "" &&    defined(title) && title != "" && defined(featuredImage.asset._ref)]    | order(startDate desc, title asc)[0...3] {    _id,    title,    "slug": slug.current,    shortDescription,    location,    programme-> { title },    featuredImage { asset, alt, hotspot, crop }  }
export type FEATURED_PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  shortDescription: string;
  location: string | null;
  programme: {
    title: string;
  };
  featuredImage: {
    asset: SanityImageAssetReference | null;
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  };
}>;

// Source: sanity/queries/reports.ts
// Variable: REPORTS_QUERY
// Query: *[_type == "report"] | order(publicationDate desc, title asc) {    _id,    title,    reportType,    description,    publicationDate,    reportingPeriod,    file {      asset-> {        _id,        url,        originalFilename,        mimeType,        size      }    },    programme-> {      _id,      title,      "slug": slug.current    },    project-> {      _id,      title,      "slug": slug.current,      status    },    coverImage {      asset,      alt,      hotspot,      crop    },    featured,    order  }
export type REPORTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  reportType:
    | "annual"
    | "financial"
    | "impact"
    | "other"
    | "programme"
    | "project"
    | "research";
  description: string;
  publicationDate: string;
  reportingPeriod: string | null;
  file: {
    asset: {
      _id: string;
      url: string;
      originalFilename: string | null;
      mimeType: string;
      size: number;
    } | null;
  };
  programme: {
    _id: string;
    title: string;
    slug: string;
  } | null;
  project: {
    _id: string;
    title: string;
    slug: string;
    status: "active" | "cancelled" | "completed" | "onHold" | "planned";
  } | null;
  coverImage: {
    asset: SanityImageAssetReference | null;
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  featured: boolean | null;
  order: number | null;
}>;

// Source: sanity/queries/site-settings.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0] {    _id,    siteTitle,    tagline,    siteDescription,    contributionCta {      label,      linkType,      internalLink-> {        _type,        "slug": slug.current      },      url,      openInNewTab    },    getInvolvedCta {      label,      linkType,      internalLink-> {        _type,        "slug": slug.current      },      url,      openInNewTab    },    socialLinks[] {      platform,      url    },    footerDescription,    copyrightText,    seo {      metaTitle,      metaDescription,      socialImage {        asset,        crop,        hotspot,        alt      },      noIndex    }  }
export type SITE_SETTINGS_QUERY_RESULT = {
  _id: "siteSettings";
  siteTitle: string;
  tagline: string;
  siteDescription: string;
  contributionCta: {
    label: string;
    linkType: "external" | "internal";
    internalLink:
      | {
          _type: "campaign";
          slug: string;
        }
      | {
          _type: "event";
          slug: string;
        }
      | {
          _type: "opportunity";
          slug: string;
        }
      | {
          _type: "programme";
          slug: string;
        }
      | {
          _type: "project";
          slug: string;
        }
      | {
          _type: "story";
          slug: string;
        }
      | null;
    url: string | null;
    openInNewTab: boolean | null;
  } | null;
  getInvolvedCta: {
    label: string;
    linkType: "external" | "internal";
    internalLink:
      | {
          _type: "campaign";
          slug: string;
        }
      | {
          _type: "event";
          slug: string;
        }
      | {
          _type: "opportunity";
          slug: string;
        }
      | {
          _type: "programme";
          slug: string;
        }
      | {
          _type: "project";
          slug: string;
        }
      | {
          _type: "story";
          slug: string;
        }
      | null;
    url: string | null;
    openInNewTab: boolean | null;
  } | null;
  socialLinks: Array<{
    platform:
      | "facebook"
      | "instagram"
      | "linkedin"
      | "tiktok"
      | "whatsapp"
      | "x"
      | "youtube";
    url: string;
  }> | null;
  footerDescription: string | null;
  copyrightText: string | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    socialImage: {
      asset: SanityImageAssetReference | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      alt: string;
    } | null;
    noIndex: boolean | null;
  } | null;
} | null;

// Source: sanity/queries/stories.ts
// Variable: STORIES_QUERY
// Query: *[_type == "story"] | order(publishedAt desc, title asc) {    _id,    title,    "slug": slug.current,    storyType,    excerpt,    publishedAt,    programme-> {      _id,      title,      "slug": slug.current    },    project-> {      _id,      title,      "slug": slug.current    },    campaign-> {      _id,      title,      "slug": slug.current    },    featuredImage {      asset,      alt,      hotspot,      crop    },    featured  }
export type STORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  storyType: "impact" | "news" | "update";
  excerpt: string;
  publishedAt: string;
  programme: {
    _id: string;
    title: string;
    slug: string;
  } | null;
  project: {
    _id: string;
    title: string;
    slug: string;
  } | null;
  campaign: {
    _id: string;
    title: string;
    slug: string;
  } | null;
  featuredImage: {
    asset: SanityImageAssetReference | null;
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  };
  featured: boolean | null;
}>;

// Source: sanity/queries/stories.ts
// Variable: STORY_BY_SLUG_QUERY
// Query: *[_type == "story" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    storyType,    excerpt,    content[] {      ...,      markDefs[] {        ...,        _type == "internalLink" => {          ...,          reference-> {            _type,            "slug": slug.current          }        }      },      _type == "image" => {        asset,        alt,        caption,        hotspot,        crop      }    },    publishedAt,    programme-> {      _id,      title,      "slug": slug.current,      shortDescription    },    project-> {      _id,      title,      "slug": slug.current,      shortDescription,      status    },    campaign-> {      _id,      title,      "slug": slug.current,      shortDescription,      status    },    featuredImage {      asset,      alt,      hotspot,      crop    },    featured,    seo {      metaTitle,      metaDescription,      socialImage {        asset,        crop,        hotspot,        alt      },      noIndex    }  }
export type STORY_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  storyType: "impact" | "news" | "update";
  excerpt: string;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<
          | {
              href: string;
              openInNewTab?: boolean;
              _type: "externalLink";
              _key: string;
            }
          | {
              reference:
                | {
                    _type: "campaign";
                    slug: string;
                  }
                | {
                    _type: "event";
                    slug: string;
                  }
                | {
                    _type: "opportunity";
                    slug: string;
                  }
                | {
                    _type: "programme";
                    slug: string;
                  }
                | {
                    _type: "project";
                    slug: string;
                  }
                | {
                    _type: "story";
                    slug: string;
                  };
              _type: "internalLink";
              _key: string;
            }
        > | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset: SanityImageAssetReference | null;
        media?: unknown;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        alt: string;
        caption: string | null;
        _type: "image";
        _key: string;
        markDefs: null;
      }
  >;
  publishedAt: string;
  programme: {
    _id: string;
    title: string;
    slug: string;
    shortDescription: string;
  } | null;
  project: {
    _id: string;
    title: string;
    slug: string;
    shortDescription: string;
    status: "active" | "cancelled" | "completed" | "onHold" | "planned";
  } | null;
  campaign: {
    _id: string;
    title: string;
    slug: string;
    shortDescription: string;
    status: "active" | "cancelled" | "completed" | "paused" | "upcoming";
  } | null;
  featuredImage: {
    asset: SanityImageAssetReference | null;
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  };
  featured: boolean | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    socialImage: {
      asset: SanityImageAssetReference | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      alt: string;
    } | null;
    noIndex: boolean | null;
  } | null;
} | null;

// Source: sanity/queries/team-members.ts
// Variable: TEAM_MEMBERS_QUERY
// Query: *[_type == "teamMember"] | order(group asc, order asc, name asc) {    _id,    name,    role,    group,    bio,    photo {      asset,      alt,      hotspot,      crop    },    linkedinUrl,    order  }
export type TEAM_MEMBERS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  role: string;
  group: "advisory" | "board" | "leadership" | "team";
  bio: string | null;
  photo: {
    asset: SanityImageAssetReference | null;
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  };
  linkedinUrl: string | null;
  order: number;
}>;

// Source: sanity/queries/team-members.ts
// Variable: TEAM_CARDS_QUERY
// Query: *[_type == "teamMember" && defined(name) && name != "" && defined(role) && role != "" && defined(photo.asset._ref)]    | order(group asc, order asc, name asc) {      _id, name, role, photo { asset, alt, hotspot, crop }    }
export type TEAM_CARDS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  role: string;
  photo: {
    asset: SanityImageAssetReference | null;
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  };
}>;

// Source: sanity/queries/testimonials.ts
// Variable: TESTIMONIALS_QUERY
// Query: *[_type == "testimonial"] | order(order asc, name asc) {    _id,    quote,    name,    testimonialType,    role,    organisation,    programme-> {      _id,      title,      "slug": slug.current    },    project-> {      _id,      title,      "slug": slug.current,      status    },    photo {      asset,      alt,      hotspot,      crop    },    featured,    order  }
export type TESTIMONIALS_QUERY_RESULT = Array<{
  _id: string;
  quote: string;
  name: string;
  testimonialType:
    "community" | "other" | "participant" | "partner" | "volunteer";
  role: string | null;
  organisation: string | null;
  programme: {
    _id: string;
    title: string;
    slug: string;
  } | null;
  project: {
    _id: string;
    title: string;
    slug: string;
    status: "active" | "cancelled" | "completed" | "onHold" | "planned";
  } | null;
  photo: {
    asset: SanityImageAssetReference | null;
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  featured: boolean | null;
  order: number;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "campaign"] | order(startDate desc, title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    shortDescription,\n    status,\n    startDate,\n    endDate,\n    goalAmount,\n    currency,\n\n    programme-> {\n      _id,\n      title,\n      "slug": slug.current\n    },\n\n    project-> {\n      _id,\n      title,\n      "slug": slug.current\n    },\n\n    featuredImage {\n      asset,\n      alt,\n      hotspot,\n      crop\n    },\n\n    featured\n  }\n': CAMPAIGNS_QUERY_RESULT;
    '\n  *[_type == "campaign" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    shortDescription,\n\n    content[] {\n      ...,\n\n      markDefs[] {\n        ...,\n\n        _type == "internalLink" => {\n          ...,\n          reference-> {\n            _type,\n            "slug": slug.current\n          }\n        }\n      },\n\n      _type == "image" => {\n        asset,\n        alt,\n        caption,\n        hotspot,\n        crop\n      }\n    },\n\n    status,\n    startDate,\n    endDate,\n    goalAmount,\n    currency,\n\n    programme-> {\n      _id,\n      title,\n      "slug": slug.current,\n      shortDescription\n    },\n\n    project-> {\n      _id,\n      title,\n      "slug": slug.current,\n      shortDescription,\n      status\n    },\n\n    featuredImage {\n      asset,\n      alt,\n      hotspot,\n      crop\n    },\n\n    featured,\n\n    seo {\n      metaTitle,\n      metaDescription,\n      socialImage {\n        asset,\n        crop,\n        hotspot,\n        alt\n      },\n      noIndex\n    }\n  }\n': CAMPAIGN_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "contactInformation" && _id == "contactInformation"][0] {\n    _id,\n    primaryEmail,\n    secondaryEmail,\n    primaryPhone,\n    secondaryPhone,\n    whatsappNumber,\n\n    addressLine,\n    district,\n    city,\n    country,\n    postalAddress,\n    mapUrl,\n\n    officeHours[] {\n      days,\n      hours\n    }\n  }\n': CONTACT_INFORMATION_QUERY_RESULT;
    '\n  *[_type == "event"] | order(startAt asc, title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    shortDescription,\n    startAt,\n    endAt,\n    format,\n    venue,\n    location,\n\n    programme-> {\n      _id,\n      title,\n      "slug": slug.current\n    },\n\n    project-> {\n      _id,\n      title,\n      "slug": slug.current\n    },\n\n    featuredImage {\n      asset,\n      alt,\n      hotspot,\n      crop\n    },\n\n    featured\n  }\n': EVENTS_QUERY_RESULT;
    '\n  *[_type == "event" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    shortDescription,\n\n    content[] {\n      ...,\n\n      markDefs[] {\n        ...,\n\n        _type == "internalLink" => {\n          ...,\n          reference-> {\n            _type,\n            "slug": slug.current\n          }\n        }\n      },\n\n      _type == "image" => {\n        asset,\n        alt,\n        caption,\n        hotspot,\n        crop\n      }\n    },\n\n    startAt,\n    endAt,\n    format,\n    venue,\n    location,\n    onlineUrl,\n\n    programme-> {\n      _id,\n      title,\n      "slug": slug.current,\n      shortDescription\n    },\n\n    project-> {\n      _id,\n      title,\n      "slug": slug.current,\n      shortDescription,\n      status\n    },\n\n    participationLink {\n      label,\n      linkType,\n      internalLink-> {\n        _type,\n        "slug": slug.current\n      },\n      url,\n      openInNewTab\n    },\n\n    featuredImage {\n      asset,\n      alt,\n      hotspot,\n      crop\n    },\n\n    featured,\n\n    seo {\n      metaTitle,\n      metaDescription,\n      socialImage {\n        asset,\n        crop,\n        hotspot,\n        alt\n      },\n      noIndex\n    }\n  }\n': EVENT_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "faq"] | order(category asc, order asc, question asc) {\n    _id,\n    question,\n    answer,\n    category,\n    featured,\n    order\n  }\n': FAQS_QUERY_RESULT;
    '\n  *[_type == "impactMetric"] | order(order asc, title asc) {\n    _id,\n    title,\n    value,\n    prefix,\n    suffix,\n    description,\n    asOfDate,\n\n    programme-> {\n      _id,\n      title,\n      "slug": slug.current\n    },\n\n    project-> {\n      _id,\n      title,\n      "slug": slug.current,\n      status\n    },\n\n    featured,\n    order\n  }\n': IMPACT_METRICS_QUERY_RESULT;
    '\n  *[_type == "impactMetric" && featured == true && title != "" && defined(title) && defined(value)]\n    | order(order asc, title asc)[0...4] {\n      _id, title, value, prefix, suffix\n    }\n': FEATURED_IMPACT_METRICS_QUERY_RESULT;
    '\n  *[_type == "opportunity"] | order(deadline asc, title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    opportunityType,\n    shortDescription,\n    mode,\n    location,\n    deadline,\n\n    programme-> {\n      _id,\n      title,\n      "slug": slug.current\n    },\n\n    project-> {\n      _id,\n      title,\n      "slug": slug.current\n    },\n\n    featuredImage {\n      asset,\n      alt,\n      hotspot,\n      crop\n    },\n\n    featured\n  }\n': OPPORTUNITIES_QUERY_RESULT;
    '\n  *[_type == "opportunity" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    opportunityType,\n    shortDescription,\n\n    content[] {\n      ...,\n\n      markDefs[] {\n        ...,\n\n        _type == "internalLink" => {\n          ...,\n          reference-> {\n            _type,\n            "slug": slug.current\n          }\n        }\n      },\n\n      _type == "image" => {\n        asset,\n        alt,\n        caption,\n        hotspot,\n        crop\n      }\n    },\n\n    mode,\n    location,\n    deadline,\n\n    programme-> {\n      _id,\n      title,\n      "slug": slug.current,\n      shortDescription\n    },\n\n    project-> {\n      _id,\n      title,\n      "slug": slug.current,\n      shortDescription,\n      status\n    },\n\n    applicationLink {\n      label,\n      linkType,\n      internalLink-> {\n        _type,\n        "slug": slug.current\n      },\n      url,\n      openInNewTab\n    },\n\n    featuredImage {\n      asset,\n      alt,\n      hotspot,\n      crop\n    },\n\n    featured,\n\n    seo {\n      metaTitle,\n      metaDescription,\n      socialImage {\n        asset,\n        crop,\n        hotspot,\n        alt\n      },\n      noIndex\n    }\n  }\n': OPPORTUNITY_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "siteSettings" && _id == "siteSettings"][0].homePage {\n    hero { title, description, imageAlt, image { asset, alt, crop, hotspot } },\n    introduction { title, description },\n    impact { title },\n    work { title, description },\n    projects { title, description },\n    involvement { title, description, volunteerDescription, partnerDescription, supportDescription },\n    contribution { title, description },\n    seo { metaTitle, metaDescription, noIndex, socialImage { asset, alt, crop, hotspot } }\n  }\n': HOME_CONTENT_QUERY_RESULT;
    '\n  *[_type == "siteSettings" && _id == "siteSettings"][0].aboutPage {\n    introduction { title, summary, description, imageAlt, image { asset, alt, crop, hotspot } },\n    purpose { title, description, missionTitle, missionDescription, visionTitle, visionDescription },\n    story { title, description, introduction, paragraph1, paragraph2, paragraph3, closing },\n    principles { title, description, items[] { _key, title, description } },\n    team { title, description },\n    header { title, description },\n    seo { metaTitle, metaDescription, noIndex, socialImage { asset, alt, crop, hotspot } }\n  }\n': ABOUT_CONTENT_QUERY_RESULT;
    '\n  *[_type == "siteSettings" && _id == "siteSettings"][0].ourWorkPage {\n    header { title, description },\n    seo { metaTitle, metaDescription, noIndex, socialImage { asset, alt, crop, hotspot } }\n  }\n': OUR_WORK_CONTENT_QUERY_RESULT;
    '\n  *[_type == "partner"] | order(order asc, name asc) {\n    _id,\n    name,\n    partnerType,\n    description,\n    websiteUrl,\n\n    programmes[]-> {\n      _id,\n      title,\n      "slug": slug.current\n    },\n\n    projects[]-> {\n      _id,\n      title,\n      "slug": slug.current,\n      status\n    },\n\n    logo {\n      asset,\n      alt,\n      hotspot,\n      crop\n    },\n\n    featured,\n    order\n  }\n': PARTNERS_QUERY_RESULT;
    '\n  *[_type == "programme"] | order(order asc, title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    shortDescription,\n    focusAreas,\n    featuredImage {\n      asset,\n      alt,\n      hotspot,\n      crop\n    },\n    featured,\n    order\n  }\n': PROGRAMMES_QUERY_RESULT;
    '\n  *[_type == "programme" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    shortDescription,\n\n    content[] {\n      ...,\n\n      markDefs[] {\n        ...,\n\n        _type == "internalLink" => {\n          ...,\n          reference-> {\n            _type,\n            "slug": slug.current\n          }\n        }\n      },\n\n      _type == "image" => {\n        asset,\n        alt,\n        caption,\n        hotspot,\n        crop\n      }\n    },\n\n    focusAreas,\n\n    featuredImage {\n      asset,\n      alt,\n      hotspot,\n      crop\n    },\n\n    featured,\n    order,\n\n    seo {\n      metaTitle,\n      metaDescription,\n      socialImage {\n        asset,\n        crop,\n        hotspot,\n        alt\n      },\n      noIndex\n    }\n  }\n': PROGRAMME_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "programme" && defined(slug.current) && slug.current != "" && defined(title) && title != ""]\n    | order(order asc, title asc) {\n      _id, title, "slug": slug.current, shortDescription\n    }\n': PROGRAMME_CARDS_QUERY_RESULT;
    '\n  *[_type == "project"] | order(startDate desc, title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    shortDescription,\n    status,\n    startDate,\n    endDate,\n    location,\n\n    programme-> {\n      _id,\n      title,\n      "slug": slug.current\n    },\n\n    featuredImage {\n      asset,\n      alt,\n      hotspot,\n      crop\n    },\n\n    featured\n  }\n': PROJECTS_QUERY_RESULT;
    '\n  *[_type == "project" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    shortDescription,\n\n    content[] {\n      ...,\n\n      markDefs[] {\n        ...,\n\n        _type == "internalLink" => {\n          ...,\n          reference-> {\n            _type,\n            "slug": slug.current\n          }\n        }\n      },\n\n      _type == "image" => {\n        asset,\n        alt,\n        caption,\n        hotspot,\n        crop\n      }\n    },\n\n    status,\n    startDate,\n    endDate,\n    location,\n\n    programme-> {\n      _id,\n      title,\n      "slug": slug.current,\n      shortDescription\n    },\n\n    featuredImage {\n      asset,\n      alt,\n      hotspot,\n      crop\n    },\n\n    featured,\n\n    seo {\n      metaTitle,\n      metaDescription,\n      socialImage {\n        asset,\n        crop,\n        hotspot,\n        alt\n      },\n      noIndex\n    }\n  }\n': PROJECT_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "project" && featured == true &&\n    defined(slug.current) && slug.current != "" &&\n    defined(title) && title != "" && defined(featuredImage.asset._ref)]\n    | order(startDate desc, title asc)[0...3] {\n    _id,\n    title,\n    "slug": slug.current,\n    shortDescription,\n    location,\n    programme-> { title },\n    featuredImage { asset, alt, hotspot, crop }\n  }\n': FEATURED_PROJECTS_QUERY_RESULT;
    '\n  *[_type == "report"] | order(publicationDate desc, title asc) {\n    _id,\n    title,\n    reportType,\n    description,\n    publicationDate,\n    reportingPeriod,\n\n    file {\n      asset-> {\n        _id,\n        url,\n        originalFilename,\n        mimeType,\n        size\n      }\n    },\n\n    programme-> {\n      _id,\n      title,\n      "slug": slug.current\n    },\n\n    project-> {\n      _id,\n      title,\n      "slug": slug.current,\n      status\n    },\n\n    coverImage {\n      asset,\n      alt,\n      hotspot,\n      crop\n    },\n\n    featured,\n    order\n  }\n': REPORTS_QUERY_RESULT;
    '\n  *[_type == "siteSettings" && _id == "siteSettings"][0] {\n    _id,\n    siteTitle,\n    tagline,\n    siteDescription,\n\n    contributionCta {\n      label,\n      linkType,\n      internalLink-> {\n        _type,\n        "slug": slug.current\n      },\n      url,\n      openInNewTab\n    },\n\n    getInvolvedCta {\n      label,\n      linkType,\n      internalLink-> {\n        _type,\n        "slug": slug.current\n      },\n      url,\n      openInNewTab\n    },\n\n    socialLinks[] {\n      platform,\n      url\n    },\n\n    footerDescription,\n    copyrightText,\n\n    seo {\n      metaTitle,\n      metaDescription,\n      socialImage {\n        asset,\n        crop,\n        hotspot,\n        alt\n      },\n      noIndex\n    }\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "story"] | order(publishedAt desc, title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    storyType,\n    excerpt,\n    publishedAt,\n\n    programme-> {\n      _id,\n      title,\n      "slug": slug.current\n    },\n\n    project-> {\n      _id,\n      title,\n      "slug": slug.current\n    },\n\n    campaign-> {\n      _id,\n      title,\n      "slug": slug.current\n    },\n\n    featuredImage {\n      asset,\n      alt,\n      hotspot,\n      crop\n    },\n\n    featured\n  }\n': STORIES_QUERY_RESULT;
    '\n  *[_type == "story" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    storyType,\n    excerpt,\n\n    content[] {\n      ...,\n\n      markDefs[] {\n        ...,\n\n        _type == "internalLink" => {\n          ...,\n          reference-> {\n            _type,\n            "slug": slug.current\n          }\n        }\n      },\n\n      _type == "image" => {\n        asset,\n        alt,\n        caption,\n        hotspot,\n        crop\n      }\n    },\n\n    publishedAt,\n\n    programme-> {\n      _id,\n      title,\n      "slug": slug.current,\n      shortDescription\n    },\n\n    project-> {\n      _id,\n      title,\n      "slug": slug.current,\n      shortDescription,\n      status\n    },\n\n    campaign-> {\n      _id,\n      title,\n      "slug": slug.current,\n      shortDescription,\n      status\n    },\n\n    featuredImage {\n      asset,\n      alt,\n      hotspot,\n      crop\n    },\n\n    featured,\n\n    seo {\n      metaTitle,\n      metaDescription,\n      socialImage {\n        asset,\n        crop,\n        hotspot,\n        alt\n      },\n      noIndex\n    }\n  }\n': STORY_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "teamMember"] | order(group asc, order asc, name asc) {\n    _id,\n    name,\n    role,\n    group,\n    bio,\n\n    photo {\n      asset,\n      alt,\n      hotspot,\n      crop\n    },\n\n    linkedinUrl,\n    order\n  }\n': TEAM_MEMBERS_QUERY_RESULT;
    '\n  *[_type == "teamMember" && defined(name) && name != "" && defined(role) && role != "" && defined(photo.asset._ref)]\n    | order(group asc, order asc, name asc) {\n      _id, name, role, photo { asset, alt, hotspot, crop }\n    }\n': TEAM_CARDS_QUERY_RESULT;
    '\n  *[_type == "testimonial"] | order(order asc, name asc) {\n    _id,\n    quote,\n    name,\n    testimonialType,\n    role,\n    organisation,\n\n    programme-> {\n      _id,\n      title,\n      "slug": slug.current\n    },\n\n    project-> {\n      _id,\n      title,\n      "slug": slug.current,\n      status\n    },\n\n    photo {\n      asset,\n      alt,\n      hotspot,\n      crop\n    },\n\n    featured,\n    order\n  }\n': TESTIMONIALS_QUERY_RESULT;
  }
}
