/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SocialLink = {
  _type: "socialLink";
  platform:
    | "facebook"
    | "instagram"
    | "linkedin"
    | "x"
    | "youtube"
    | "tiktok"
    | "whatsapp";
  url: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  socialImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  noIndex?: boolean;
};

export type ProgrammeReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "programme";
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type CampaignReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "campaign";
};

export type StoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "story";
};

export type EventReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "event";
};

export type OpportunityReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "opportunity";
};

export type Link = {
  _type: "link";
  label: string;
  linkType: "internal" | "external";
  internalLink?:
    | ProgrammeReference
    | ProjectReference
    | CampaignReference
    | StoryReference
    | EventReference
    | OpportunityReference;
  url?: string;
  openInNewTab?: boolean;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<
        | {
            href: string;
            openInNewTab?: boolean;
            _type: "externalLink";
            _key: string;
          }
        | {
            reference:
              | ProgrammeReference
              | ProjectReference
              | CampaignReference
              | StoryReference
              | EventReference
              | OpportunityReference;
            _type: "internalLink";
            _key: string;
          }
      >;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      caption?: string;
      _type: "image";
      _key: string;
    }
>;

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question: string;
  answer: string;
  category:
    | "general"
    | "programmes"
    | "contributions"
    | "opportunities"
    | "partnerships"
    | "other";
  featured?: boolean;
  order: number;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Report = {
  _id: string;
  _type: "report";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  reportType:
    | "annual"
    | "impact"
    | "financial"
    | "programme"
    | "project"
    | "research"
    | "other";
  description: string;
  publicationDate: string;
  reportingPeriod?: string;
  file: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  programme?: ProgrammeReference;
  project?: ProjectReference;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  featured?: boolean;
  order?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote: string;
  name: string;
  testimonialType:
    "participant" | "community" | "volunteer" | "partner" | "other";
  role?: string;
  organisation?: string;
  programme?: ProgrammeReference;
  project?: ProjectReference;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  featured?: boolean;
  order: number;
};

export type ImpactMetric = {
  _id: string;
  _type: "impactMetric";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  value: number;
  prefix?: string;
  suffix?: string;
  description?: string;
  asOfDate: string;
  programme?: ProgrammeReference;
  project?: ProjectReference;
  featured?: boolean;
  order: number;
};

export type Partner = {
  _id: string;
  _type: "partner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  partnerType:
    | "strategic"
    | "funding"
    | "implementation"
    | "institutional"
    | "supporting"
    | "other";
  description?: string;
  websiteUrl?: string;
  programmes?: Array<
    {
      _key: string;
    } & ProgrammeReference
  >;
  projects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  featured?: boolean;
  order: number;
};

export type TeamMember = {
  _id: string;
  _type: "teamMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  role: string;
  group: "leadership" | "board" | "team" | "advisory";
  bio?: string;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  linkedinUrl?: string;
  order: number;
};

export type Programme = {
  _id: string;
  _type: "programme";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  shortDescription: string;
  content: BlockContent;
  focusAreas?: Array<string>;
  featuredImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  featured?: boolean;
  order: number;
  seo?: Seo;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  programme: ProgrammeReference;
  shortDescription: string;
  content: BlockContent;
  status: "planned" | "active" | "onHold" | "completed" | "cancelled";
  startDate?: string;
  endDate?: string;
  location?: string;
  featuredImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  featured?: boolean;
  seo?: Seo;
};

export type Campaign = {
  _id: string;
  _type: "campaign";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  shortDescription: string;
  content: BlockContent;
  programme: ProgrammeReference;
  project?: ProjectReference;
  status: "upcoming" | "active" | "paused" | "completed" | "cancelled";
  startDate?: string;
  endDate?: string;
  goalAmount: number;
  currency: "TZS" | "USD";
  featuredImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  featured?: boolean;
  seo?: Seo;
};

export type Story = {
  _id: string;
  _type: "story";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  storyType: "impact" | "news" | "update";
  excerpt: string;
  content: BlockContent;
  publishedAt: string;
  programme?: ProgrammeReference;
  project?: ProjectReference;
  campaign?: CampaignReference;
  featuredImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  featured?: boolean;
  seo?: Seo;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  shortDescription: string;
  content: BlockContent;
  startAt: string;
  endAt?: string;
  format: "inPerson" | "online" | "hybrid";
  venue?: string;
  location?: string;
  onlineUrl?: string;
  programme?: ProgrammeReference;
  project?: ProjectReference;
  participationLink?: Link;
  featuredImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  featured?: boolean;
  seo?: Seo;
};

export type Opportunity = {
  _id: string;
  _type: "opportunity";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  opportunityType:
    | "volunteer"
    | "internship"
    | "employment"
    | "partnership"
    | "programmeApplication"
    | "other";
  shortDescription: string;
  content: BlockContent;
  mode: "onSite" | "remote" | "hybrid";
  location?: string;
  deadline?: string;
  programme?: ProgrammeReference;
  project?: ProjectReference;
  applicationLink?: Link;
  featuredImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  featured?: boolean;
  seo?: Seo;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type ContactInformation = {
  _id: string;
  _type: "contactInformation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  primaryEmail: string;
  secondaryEmail?: string;
  primaryPhone: string;
  secondaryPhone?: string;
  whatsappNumber?: string;
  addressLine?: string;
  district?: string;
  city: string;
  country: string;
  postalAddress?: string;
  mapUrl?: string;
  officeHours?: Array<{
    days: string;
    hours: string;
    _type: "officeHoursEntry";
    _key: string;
  }>;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteTitle: string;
  tagline: string;
  siteDescription: string;
  contributionCta?: Link;
  getInvolvedCta?: Link;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  footerDescription?: string;
  copyrightText?: string;
  seo?: Seo;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SocialLink
  | SanityImageAssetReference
  | Seo
  | ProgrammeReference
  | ProjectReference
  | CampaignReference
  | StoryReference
  | EventReference
  | OpportunityReference
  | Link
  | BlockContent
  | Faq
  | SanityFileAssetReference
  | Report
  | SanityImageCrop
  | SanityImageHotspot
  | Testimonial
  | ImpactMetric
  | Partner
  | TeamMember
  | Programme
  | Project
  | Campaign
  | Story
  | Event
  | Opportunity
  | Slug
  | ContactInformation
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
